//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiteWiseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySummary
    {
        public int summary_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> total_calories_consumed { get; set; }
        public Nullable<decimal> total_calories_burned { get; set; }
        public Nullable<decimal> net_calories { get; set; }
    
        public virtual User User { get; set; }
    }
}
