//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiteWiseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodLog
    {
        public int Record_Id { get; set; }
        public int user_id { get; set; }
        public string Food_name { get; set; }
        public string Cals_Consumed { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual User User { get; set; }
    }
}
