//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiteWiseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.Meals = new HashSet<Meal>();
        }
    
        public int food_id { get; set; }
        public string name { get; set; }
        public int calories { get; set; }
        public Nullable<decimal> protein { get; set; }
        public Nullable<decimal> carbs { get; set; }
        public Nullable<decimal> fats { get; set; }
        public Nullable<decimal> fiber { get; set; }
        public string serving_size { get; set; }
        public string category { get; set; }
        public Nullable<short> is_local { get; set; }
        public Nullable<int> user_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meal> Meals { get; set; }
        public virtual User User { get; set; }
    }
}
