//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiteWiseApp
{
    using System;
    using System.Collections.Generic;

    public partial class Goal
    {
        public int goal_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<decimal> target_weight { get; set; }
        public Nullable<decimal> daily_caloric_target { get; set; }
        public Nullable<decimal> weekly_weight_change_goal { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual User User { get; set; }
    }
}
