//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiteWiseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class JamaicanRecipe
    {
        public int recipe_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> calories_per_serving { get; set; }
        public string ingredients { get; set; }
        public string instructions { get; set; }
    }
}
