//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiteWiseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int meal_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> food_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string meal_type { get; set; }
        public Nullable<System.DateTime> consumed_at { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual User User { get; set; }
    }
}
