//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiteWiseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Work_log
    {
        public string User_Name { get; set; }
        public string Exercise_Name { get; set; }
        public string category { get; set; }
        public Nullable<decimal> Total_Calories_Burnt { get; set; }
        public Nullable<decimal> duration { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
