//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiteWiseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMeasurement
    {
        public int measurement_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> waist_size { get; set; }
        public Nullable<decimal> hip_size { get; set; }
        public Nullable<decimal> chest_size { get; set; }
        public Nullable<decimal> arm_size { get; set; }
        public Nullable<decimal> leg_size { get; set; }
    
        public virtual User User { get; set; }
    }
}
