//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiteWiseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutLog
    {
        public int log_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> exercise_id { get; set; }
        public Nullable<decimal> duration { get; set; }
        public Nullable<decimal> calories_burned { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Exercis Exercis { get; set; }
        public virtual User User { get; set; }
    }
}
